### PR TITLE
Collections equality 1555

### PR DESCRIPTION
**Pull request by danieldietrich**
Hi Victor,

you did a great job! This is part of my review of your PR.

I added some changes to the Collections.equals() and hash*() methods + additional tests.
The whole source is rebased on the current master branch.

Please push the new version, then we can pull it! (Maybe you need to `push --force` because I rebased the branch)

Many thanks for your help!

Daniel

### CODE REVIEW

**Comment by danieldietrich** [comment]
Please don't be confused about the number of changes. When you merge it into your branch and push it to the upstream, you will only see my last commit added.

Basically I fixed the Collections.equals(*) methods. We are not allowed to distinguish between isOrdered() collections. I added test-cases to AbstractSortedSetTest.

Additionally I added tests to Abstract[Seq|Set|Map|Multimap]Test.

**Comment by ruslansennov** [comment]
> I see no reason we need them anymore

The only reason is to calculate hash code and equality properly in `LeafList`'s. The same should be done in `HashMap` and `HashSet` in case these methods will be removed from HAMT.

**Comment by danieldietrich** [comment]
@ruslansennov 

> The only reason is to calculate hash code and equality properly in LeafList's. The same should be done in HashMap and HashSet in case these methods will be removed from HAMT.

Ok, I will see - it is deferred to a separate issue. In Maps and Sets it is already handled, they call Collections.hashUnordered(Iterable).

**Comment by v1ctor** [comment]
Great! Thank you very much. I will do it today.

**Comment by danieldietrich** [comment]
Hi Victor,

I realized that I created a PR into your master branch, but we need it in the collection-equality-1555 branch.

I think the simplest solution is that you create a PR based on your current master (which now contains both of our changes). Then we simply close the other PR and I merge the new one.

What do you think?

**Pull request merged**
